package dtu.ux62550.wheeloffortune

val wordsAndCategories: List<Pair<String, String>> =
    listOf(
        Pair("Food and Drink", "Apple"),
        Pair("Food and Drink", "Turkey"),
        Pair("Food and Drink", "Pie"),
        Pair("Food and Drink", "Breakfast"),
        Pair("Food and Drink", "Doughnuts"),
        Pair("Food and Drink", "Fettuccine"),
        Pair("Food and Drink", "Quesadillas"),
        Pair("Food and Drink", "Passionfruit"),
        Pair("Food and Drink", "Sandwich"),
        Pair("Food and Drink", "Chocolate"),
        Pair("Food and Drink", "Apple Juice"),
        Pair("Food and Drink", "Barbecued Ribs"),
        Pair("Food and Drink", "Beef Jerky"),
        Pair("Food and Drink", "Black Licorice"),
        Pair("Food and Drink", "Clam Chowder"),
        Pair("Food and Drink", "French Fries"),
        Pair("Food and Drink", "Hot Wings"),
        Pair("Food and Drink", "Rye Bread"),
        Pair("Food and Drink", "Osso Buco"),
        Pair("Food and Drink", "Fried Eggs"),

        Pair("Place", "Turkey"),
        Pair("Place", "Archipelago"),
        Pair("Place", "Singapore"),
        Pair("Place", "Pluto"),
        Pair("Place", "Savannas"),
        Pair("Place", "Suburbia"),
        Pair("Place", "Transylvania"),
        Pair("Place", "Marketplace"),
        Pair("Place", "Junkyard"),
        Pair("Place", "Gymnasium"),
        Pair("Place", "Fairyland"),
        Pair("Place", "Animal Farm"),
        Pair("Place", "Amazon Rainforest"),
        Pair("Place", "Silicon Valley"),
        Pair("Place", "Cape Town"),
        Pair("Place", "Echo Chamber"),
        Pair("Place", "Eiffel Tower"),
        Pair("Place", "Fishing Hut"),
        Pair("Place", "General Store"),
        Pair("Place", "Hot Springs"),
        Pair("Place", "King's Landing"),
        Pair("Place", "Lafayette Square"),

        Pair("TV Show Title", "Dexter"),
        Pair("TV Show Title", "Friends"),
        Pair("TV Show Title", "Jeopardy"),
        Pair("TV Show Title", "Mythbusters"),
        Pair("TV Show Title", "Suits"),
        Pair("TV Show Title", "Sherlock"),
        Pair("TV Show Title", "Seinfeld"),
        Pair("TV Show Title", "Firefly"),
        Pair("TV Show Title", "Fargo"),
        Pair("TV Show Title", "Narcos"),
        Pair("TV Show Title", "Succession"),
        Pair("TV Show Title", "Top Gear"),
        Pair("TV Show Title", "Breaking Bad"),
        Pair("TV Show Title", "Planet Earth"),
        Pair("TV Show Title", "The Wire"),
        Pair("TV Show Title", "Game of Thrones"),
        Pair("TV Show Title", "Family Feud"),
        Pair("TV Show Title", "Knight Rider"),
        Pair("TV Show Title", "Mad Men"),
        Pair("TV Show Title", "Pawn Stars"),
        Pair("TV Show Title", "Silicon Valley"),
        Pair("TV Show Title", "True Detective"),

        Pair("Occupation", "Bartender"),
        Pair("Occupation", "Astronaut"),
        Pair("Occupation", "Chauffeur"),
        Pair("Occupation", "Dishwasher"),
        Pair("Occupation", "Handyman"),
        Pair("Occupation", "Doorman"),
        Pair("Occupation", "Newscaster"),
        Pair("Occupation", "Zookeeper"),
        Pair("Occupation", "Pilot"),
        Pair("Occupation", "Mechanic"),
        Pair("Occupation", "Bank Teller"),
        Pair("Occupation", "Baseball Coach"),
        Pair("Occupation", "Attorney General"),
        Pair("Occupation", "Civil Engineer"),
        Pair("Occupation", "Voice Actor"),
        Pair("Occupation", "Truck Driver"),
        Pair("Occupation", "Private Detective"),
        Pair("Occupation", "Postal Worker"),
        Pair("Occupation", "Movie Critic"),
        Pair("Occupation", "Investigative Journalist")
    )
